version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - nacos
    environment:
      - NACOS_SERVER=nacos:8848
      - NACOS_NAMESPACE=public
      - NACOS_LOG_DIR=/var/log/nacos
      - NACOS_CACHE_DIR=/var/cache/nacos

  nacos:
    image: nacos/nacos-server:latest
    ports:
      - "8848:8848"
    environment:
      MODE: standalone
    volumes:
      - nacos_data:/home/nacos/data

volumes:
  nacos_data: